export const LUCIDE_ICON_NAMES = [
  'Activity', 'AlarmClock', 'Album', 'Anchor', 'Aperture', 'Apple', 'Archive',
  'Armchair', 'Atom', 'Award', 'Baby', 'Backpack', 'Banana', 'Banknote',
  'BarChart', 'Battery', 'Beaker', 'Bean', 'Bed', 'Beef', 'Beer', 'Bell',
  'Bike', 'Binary', 'Bird', 'Bitcoin', 'Blocks', 'Bluetooth', 'Bolt',
  'Bone', 'Book', 'BookOpen', 'Bookmark', 'Bot', 'Box', 'Brain', 'Briefcase',
  'Brush', 'Bug', 'Building', 'Bus', 'Cake', 'Calculator', 'Calendar',
  'Camera', 'Candy', 'Car', 'Carrot', 'Castle', 'Cat', 'Cherry', 'ChefHat',
  'Chrome', 'Church', 'Circle', 'Clapperboard', 'Clipboard', 'Clock',
  'Cloud', 'Clover', 'Code', 'Coffee', 'Cog', 'Coins', 'Compass', 'Cookie',
  'Copy', 'Cpu', 'CreditCard', 'Croissant', 'Crop', 'Crown', 'Database',
  'Diamond', 'DollarSign', 'Donut', 'Drama', 'Drill', 'Droplet', 'Drum',
  'Dumbbell', 'Ear', 'Earth', 'Egg', 'Eye', 'Factory', 'Feather', 'Figma',
  'Film', 'Filter', 'Fingerprint', 'Fish', 'Flag', 'Flame', 'FlaskConical',
  'Flower', 'Focus', 'Folder', 'Footprints', 'Frame', 'Fuel', 'Gamepad2',
  'Gauge', 'Gavel', 'Gem', 'Ghost', 'Gift', 'GitBranch', 'Github', 'Glasses',
  'Globe', 'Goal', 'Grape', 'Grid', 'Guitar', 'Hammer', 'Hand', 'Handshake',
  'HardDrive', 'Hash', 'Headphones', 'Heart', 'HeartPulse', 'Hexagon',
  'Home', 'Hotel', 'Hourglass', 'House', 'IceCream', 'Image', 'Inbox',
  'Infinity', 'Info', 'Instagram', 'Joystick', 'Key', 'Keyboard', 'Lamp',
  'Landmark', 'Languages', 'Laptop', 'Laugh', 'Layers', 'Leaf', 'Lemon',
  'Library', 'Lightbulb', 'Link', 'Linkedin', 'List', 'Lock', 'Luggage',
  'Magnet', 'Mail', 'Map', 'MapPin', 'Medal', 'Megaphone', 'MessageCircle',
  'Mic', 'Milk', 'Monitor', 'Moon', 'Mountain', 'Mouse', 'Music',
  'Navigation', 'Network', 'Newspaper', 'Notebook', 'Package', 'Paintbrush',
  'Palette', 'Paperclip', 'PartyPopper', 'PawPrint', 'Pen', 'Pencil',
  'Phone', 'Piano', 'Pickaxe', 'Pill', 'Pin', 'Pizza', 'Plane', 'Play',
  'Plug', 'Pocket', 'Podcast', 'Popcorn', 'Power', 'Printer', 'Puzzle',
  'QrCode', 'Rabbit', 'Radar', 'Radio', 'Rainbow', 'Receipt', 'Recycle',
  'Rocket', 'Route', 'Rss', 'Ruler', 'Sailboat', 'Salad', 'Satellite',
  'Save', 'Scale', 'School', 'Scissors', 'Search', 'Send', 'Server',
  'Settings', 'Share', 'Shield', 'Ship', 'Shirt', 'ShoppingBag',
  'ShoppingCart', 'Shrub', 'Siren', 'Skull', 'Slack', 'Smile', 'Snowflake',
  'Sofa', 'Sparkles', 'Speaker', 'Sprout', 'Square', 'Squirrel', 'Stamp',
  'Star', 'Stethoscope', 'Sticker', 'Store', 'Sun', 'Swords', 'Syringe',
  'Table', 'Tablet', 'Tag', 'Target', 'Telescope', 'Tent', 'Terminal',
  'TestTube', 'ThumbsUp', 'Ticket', 'Timer', 'Train', 'Trash', 'Tree',
  'TreePalm', 'TrendingUp', 'Triangle', 'Trophy', 'Truck', 'Tv', 'Twitter',
  'Umbrella', 'University', 'Upload', 'User', 'Users', 'Utensils', 'Vault',
  'Video', 'Wallet', 'Wand', 'Warehouse', 'Watch', 'Waves', 'Webcam',
  'Webhook', 'Wheat', 'Wifi', 'Wind', 'Wine', 'Workflow', 'Wrench',
  'Youtube', 'Zap',
]
